/**
 * Knowledge Item Creation Service
 *
 * Handles creation of knowledge items with automatic embedding generation.
 */

import { PrismaClient } from '@prisma/client';
import { generateEmbedding } from '../embeddings';
import type { CreateKnowledgeItemInput } from '../validations/knowledge';
import { findDuplicates, DuplicationError } from './deduplication';

const prisma = new PrismaClient();

export interface CreateKnowledgeItemResult {
  id: number;
  title: string;
  content: string;
  category: string;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
  embeddingProvider: 'ollama' | 'openai';
  embeddingDuration: number;
}

export class KnowledgeCreationError extends Error {
  constructor(
    message: string,
    public code: string,
    public statusCode: number = 500,
    public override cause?: unknown
  ) {
    super(message);
    this.name = 'KnowledgeCreationError';
  }
}

// Re-export DuplicationError for API consumers
export { DuplicationError } from './deduplication';
export type { DuplicateCandidate } from './deduplication';

/**
 * Create a knowledge item with automatic embedding generation
 *
 * Process:
 * 1. Validate input (caller's responsibility via Zod)
 * 2. Check for duplicates (US-089) - unless allowDuplicates=true
 * 3. Generate embedding from title + content
 * 4. Insert into database (tsvector auto-generated by trigger)
 * 5. Return created item with metadata
 *
 * @param data - Knowledge item data
 * @param allowDuplicates - Skip duplicate detection (default: false)
 * @returns Created knowledge item with embedding metadata
 * @throws KnowledgeCreationError if creation fails
 * @throws DuplicationError if duplicate found (and allowDuplicates=false)
 *
 * @example
 * ```typescript
 * const item = await createKnowledgeItem({
 *   title: 'PostgreSQL Indexing',
 *   content: 'How to create indexes...',
 *   category: 'Database',
 *   tags: ['postgresql', 'performance']
 * });
 * console.log(`Created item ${item.id} using ${item.embeddingProvider}`);
 * ```
 */
export async function createKnowledgeItem(
  data: CreateKnowledgeItemInput,
  allowDuplicates: boolean = false
): Promise<CreateKnowledgeItemResult> {
  const { projectId, title, content, category, tags } = data;

  try {
    // Generate embedding from title + content (weighted combination)
    // Title gets more weight since it's the primary descriptor
    const embeddingText = `${title}\n\n${content}`;

    const embeddingResult = await generateEmbedding(embeddingText);

    // US-089: Check for duplicates (unless explicitly allowed)
    if (!allowDuplicates) {
      const deduplicationResult = await findDuplicates({
        projectId,
        title,
        embedding: embeddingResult.embedding,
        category,
        similarityThreshold: 0.95,
        limit: 5,
      });

      if (deduplicationResult.isDuplicate || deduplicationResult.candidates.length > 0) {
        throw new DuplicationError(
          deduplicationResult.suggestion ||
            `Found ${deduplicationResult.candidates.length} similar item(s). Use allowDuplicates=true to create anyway.`,
          'DUPLICATE_DETECTED',
          400,
          deduplicationResult.candidates
        );
      }
    }

    // Convert embedding array to PostgreSQL vector string
    const embeddingVector = `[${embeddingResult.embedding.join(',')}]`;

    // Insert into database using raw query (Prisma doesn't support vector type natively)
    // Populate contentTsvector with title (weight A) + content (weight B) for fulltext search
    const result = await prisma.$queryRaw<
      Array<{
        id: number;
        title: string;
        content: string;
        category: string;
        tags: string[];
        createdAt: Date;
        updatedAt: Date;
      }>
    >`
      INSERT INTO knowledge_items (
        "projectId",
        title,
        content,
        category,
        tags,
        embedding,
        "contentTsvector",
        "createdAt",
        "updatedAt"
      )
      VALUES (
        ${projectId},
        ${title},
        ${content},
        ${category},
        ${tags}::text[],
        ${embeddingVector}::vector(768),
        setweight(to_tsvector('english', ${title}), 'A') ||
        setweight(to_tsvector('english', ${content}), 'B'),
        NOW(),
        NOW()
      )
      RETURNING id, title, content, category, tags, "createdAt", "updatedAt"
    `;

    if (!result || result.length === 0 || !result[0]) {
      throw new KnowledgeCreationError(
        'Failed to create knowledge item: No result returned',
        'CREATION_FAILED',
        500
      );
    }

    const created = result[0];

    return {
      id: created.id,
      title: created.title,
      content: created.content,
      category: created.category,
      tags: created.tags,
      createdAt: created.createdAt,
      updatedAt: created.updatedAt,
      embeddingProvider: embeddingResult.provider,
      embeddingDuration: embeddingResult.duration,
    };
  } catch (error) {
    // Handle specific error types
    if (error instanceof KnowledgeCreationError) {
      throw error;
    }

    // Handle embedding generation errors
    if (error instanceof Error && error.name.includes('Embedding')) {
      throw new KnowledgeCreationError(
        `Failed to generate embedding: ${error.message}`,
        'EMBEDDING_FAILED',
        503, // Service Unavailable
        error
      );
    }

    // Handle database errors
    if (error instanceof Error && error.message.includes('Prisma')) {
      throw new KnowledgeCreationError(
        `Database error: ${error.message}`,
        'DATABASE_ERROR',
        500,
        error
      );
    }

    // Generic error
    throw new KnowledgeCreationError(
      `Failed to create knowledge item: ${error instanceof Error ? error.message : 'Unknown error'}`,
      'UNKNOWN_ERROR',
      500,
      error
    );
  }
}

/**
 * Batch create multiple knowledge items
 *
 * More efficient than creating items one-by-one.
 * Generates embeddings in parallel where possible.
 *
 * @param items - Array of knowledge items to create
 * @returns Array of created items
 * @throws KnowledgeCreationError if any creation fails
 *
 * @example
 * ```typescript
 * const items = await batchCreateKnowledgeItems([
 *   { title: 'Item 1', content: '...', category: 'Tech', tags: [] },
 *   { title: 'Item 2', content: '...', category: 'Tech', tags: [] }
 * ]);
 * ```
 */
export async function batchCreateKnowledgeItems(
  items: CreateKnowledgeItemInput[]
): Promise<CreateKnowledgeItemResult[]> {
  if (items.length === 0) {
    return [];
  }

  // For now, create sequentially to maintain simplicity
  // Can optimize with batch embedding generation later
  const results: CreateKnowledgeItemResult[] = [];

  for (const item of items) {
    const result = await createKnowledgeItem(item);
    results.push(result);
  }

  return results;
}
