/**
 * WikiCard Component
 *
 * Individual wiki page preview card
 * Memoized with React.memo for list performance
 */

'use client';

import Link from 'next/link';
import { Clock } from 'lucide-react';
import { memo } from 'react';
import { useProject } from '@/lib/project/ProjectContext';

interface WikiCardProps {
  page: {
    id: string;
    title: string;
    excerpt: string;
    highlight?: string;
    category: string;
    path: string;
    updatedAt: Date;
    stats?: {
      views: number;
      helpfulRatio: number | null;
      popularity: number | null;
    };
    autoGenerated?: boolean;
  };
}

export const WikiCard = memo(function WikiCard({ page }: WikiCardProps) {
  const { id, title, excerpt, highlight, category, path, updatedAt, stats, autoGenerated } = page;
  const { buildHref } = useProject();

  // Format timestamp (relative time)
  const formatDistanceToNow = (date: Date): string => {
    const now = new Date();
    const diffInSeconds = Math.floor((now.getTime() - new Date(date).getTime()) / 1000);

    if (diffInSeconds < 60) return 'just now';
    if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)} minutes ago`;
    if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)} hours ago`;
    if (diffInSeconds < 2592000) return `${Math.floor(diffInSeconds / 86400)} days ago`;
    return `${Math.floor(diffInSeconds / 2592000)} months ago`;
  };

  const timeAgo = formatDistanceToNow(updatedAt);

  return (
    <article className="neu-raised smooth-transition group rounded-3xl p-6 hover:-translate-y-1 hover:shadow-2xl">
      <Link
        href={buildHref(`/wiki/${path.replace(/^\//, '')}`)}
        className="block rounded-2xl focus:outline-none focus:ring-2 focus:ring-coral/50"
      >
        {/* Category & System Badges */}
        <div className="mb-3 flex items-center gap-2">
          {category && category !== 'Uncategorized' && (
            <span
              className="inline-block rounded-full bg-coral/10 px-3 py-1 text-xs font-semibold text-coral"
              aria-label={`Category: ${category}`}
            >
              {category}
            </span>
          )}

          {autoGenerated && (
            <span
              className="inline-block rounded-full bg-slate-800 px-2 py-1 text-[10px] font-medium uppercase tracking-wider text-slate-400"
              title="System generated page"
            >
              System
            </span>
          )}
        </div>

        {/* Title */}
        <h3 className="smooth-transition mb-2 text-xl font-bold text-white group-hover:text-coral">
          {title}
        </h3>

        {(highlight || excerpt) && (
          <p className="mb-4 line-clamp-3 text-sm text-slate">
            {renderHighlightedText(highlight || excerpt)}
          </p>
        )}

        {stats && (
          <div className="mb-4 flex items-center gap-3 text-xs text-slate">
            <span>{stats.views.toLocaleString()} views</span>
            {stats.helpfulRatio !== null && stats.helpfulRatio !== undefined && (
              <span>{stats.helpfulRatio}% helpful</span>
            )}
            {stats.popularity !== null && stats.popularity !== undefined && (
              <span className="rounded-full bg-black/20 px-2 py-0.5 text-white/70">
                Pop {stats.popularity.toFixed(1)}
              </span>
            )}
          </div>
        )}

        {/* Last Updated */}
        <div className="flex items-center gap-2 text-xs text-slate">
          <Clock className="h-3 w-3" aria-hidden="true" />
          <time dateTime={new Date(updatedAt).toISOString()}>Updated {timeAgo}</time>
        </div>
      </Link>
    </article>
  );
});

function renderHighlightedText(text: string): React.ReactNode {
  const segments = text.split('**');
  return (
    <>
      {segments.map((segment, index) =>
        index % 2 === 1 ? (
          <mark
            key={`highlight-${index}`}
            className="bg-coral/20 font-semibold text-white"
            data-highlight="true"
          >
            {segment}
          </mark>
        ) : (
          <span key={`text-${index}`}>{segment}</span>
        )
      )}
    </>
  );
}
