import { prisma } from '@/lib/prisma';
import { revalidatePath } from 'next/cache';
import { createLogger } from '@/lib/logger';

const log = createLogger({ module: 'Wiki:SyncOnboarding' });

/**
 * Sync Onboarding Documents to Wiki
 *
 * Copies generated onboarding documents (from Session 2) to WikiPage records.
 * This makes them available in the Wiki UI for long-term reference.
 *
 * Mapping:
 * - Document -> WikiPage
 * - Category -> Wiki Category
 * - Filename -> Title & Slug
 */
export async function syncOnboardingToWiki(projectId: number) {
  log.info({ projectId }, 'Starting wiki sync');

  // 1. Fetch Project and Session 2 documents
  const [project, session2] = await Promise.all([
    prisma.project.findUnique({
      where: { id: projectId },
      select: { name: true },
    }),
    prisma.onboardingSession.findUnique({
      where: {
        projectId_sessionNumber: { projectId, sessionNumber: 2 },
      },
      include: {
        documents: true,
      },
    }),
  ]);

  if (!project) {
    log.error({ projectId }, 'Project not found');
    return;
  }

  if (!session2 || session2.documents.length === 0) {
    log.info('No Session 2 documents found to sync');
    return;
  }

  const documents = session2.documents;
  log.info({ count: documents.length }, 'Found documents to sync');

  const projectSlug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

  // 2. Ensure "Project Documentation" parent page exists
  // Find or create root page for project documentation
  // We'll use "reference" category for now, or map based on document category

  // Map document category to wiki category
  const categoryMap: Record<string, string> = {
    planning: 'getting-started',
    architecture: 'reference',
    implementation: 'guides',
    operations: 'guides',
  };

  let syncedCount = 0;

  for (const doc of documents) {
    try {
      const wikiCategory = categoryMap[doc.category || 'planning'] || 'reference';

      // Clean filename to create title and slug
      // "01-PRD.md" -> "PRD"
      // "13-Project-Plan.md" -> "Project Plan"
      const nameWithoutExt = doc.filename.replace(/\.md$/i, '');
      const titlePart = nameWithoutExt.replace(/^\d+-/, '').replace(/-/g, ' ');

      const slug = nameWithoutExt.toLowerCase();
      // Use project-slug namespacing for global uniqueness compliance
      const wikiPath = `/${projectSlug}/docs/${slug}`;

      // Check if page exists
      const existingPage = await prisma.wikiPage.findFirst({
        where: {
          projectId,
          // We'll match on title or path logic if we want to update?
          // Ideally we match on a predictable path.
          path: wikiPath,
        },
      });

      if (existingPage) {
        // Update content if it's auto-generated (don't overwrite user edits if we can help it?)
        // For now, last write wins for synchronization.
        await prisma.wikiPage.update({
          where: { id: existingPage.id },
          data: {
            content: doc.content,
            updatedAt: new Date(),
          },
        });
      } else {
        await prisma.wikiPage.create({
          data: {
            projectId,
            title: titlePart,
            path: wikiPath,
            content: doc.content,
            category: wikiCategory,
            excerpt: `Auto-generated ${doc.category} document from Onboarding Session 2.`,
            autoGenerated: true,
            version: 1,
            lastEditedBy: 'Onboarding Agent',
          },
        });
      }
      syncedCount++;
    } catch (error) {
      log.error(
        { error: error instanceof Error ? error.message : String(error), filename: doc.filename },
        'Failed to sync document'
      );
    }
  }

  log.info({ syncedCount }, 'Wiki sync complete');

  // Revalidate wiki paths
  revalidatePath('/wiki');
  revalidatePath(`/wiki/${projectId}`);
}
