/**
 * API Route: POST /api/projects/[id]/wiki/refresh
 *
 * Refresh project wiki pages from latest system templates.
 * Only updates pages that are still marked autoGenerated=true
 * and haven't been manually edited.
 *
 * Query params:
 * - preview=true: Returns diff without applying changes
 *
 * Security:
 * - Requires authentication
 * - Only project owner can refresh wikis
 */

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { requireUser } from '@/lib/auth-server';
import { INITIAL_TEMPLATES } from '@/lib/wiki/system-templates';

interface RefreshResult {
  updated: Array<{ title: string; path: string; reason: string }>;
  skipped: Array<{ title: string; path: string; reason: string }>;
  unchanged: Array<{ title: string; path: string }>;
  preview: boolean;
}

export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const user = await requireUser();
    const projectId = parseInt(params.id, 10);

    if (isNaN(projectId)) {
      return NextResponse.json({ error: 'Invalid project ID' }, { status: 400 });
    }

    // Check project ownership
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      select: { id: true, name: true, ownerId: true },
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    if (project.ownerId !== user.id) {
      return NextResponse.json({ error: 'Forbidden - only project owner can refresh wikis' }, { status: 403 });
    }

    // Check if preview mode
    const { searchParams } = new URL(request.url);
    const isPreview = searchParams.get('preview') === 'true';

    // Get project slug for path matching
    const projectSlug = project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

    // Fetch project's wiki pages that were auto-generated
    const existingPages = await prisma.wikiPage.findMany({
      where: { projectId },
      select: {
        id: true,
        title: true,
        path: true,
        content: true,
        autoGenerated: true,
        lastEditedBy: true,
        version: true,
      },
    });

    const result: RefreshResult = {
      updated: [],
      skipped: [],
      unchanged: [],
      preview: isPreview,
    };

    // Process each template
    for (const template of INITIAL_TEMPLATES) {
      // Calculate what the path would be for this project
      const expectedPath = template.path.replace(/^\/[^\/]+/, `/${projectSlug}`);

      // Find matching page in project
      const existingPage = existingPages.find((p) => p.path === expectedPath);

      if (!existingPage) {
        // Page doesn't exist - will be created
        result.updated.push({
          title: template.title,
          path: expectedPath,
          reason: 'Page will be created (does not exist)',
        });

        if (!isPreview) {
          await prisma.wikiPage.create({
            data: {
              projectId,
              title: template.title,
              path: expectedPath,
              category: template.category,
              content: template.content,
              autoGenerated: true,
              version: 1,
              lastEditedBy: 'System Refresh',
            },
          });
        }
        continue;
      }

      // Page exists - check if it can be updated
      if (!existingPage.autoGenerated) {
        // Not auto-generated - skip
        result.skipped.push({
          title: existingPage.title,
          path: existingPage.path,
          reason: 'Not auto-generated (manually created page)',
        });
        continue;
      }

      if (existingPage.lastEditedBy !== 'System Clone' && existingPage.lastEditedBy !== 'System Bootstrap' && existingPage.lastEditedBy !== 'System Refresh') {
        // User has edited - skip
        result.skipped.push({
          title: existingPage.title,
          path: existingPage.path,
          reason: `User edited (last edited by: ${existingPage.lastEditedBy})`,
        });
        continue;
      }

      // Check if content actually differs
      if (existingPage.content === template.content) {
        result.unchanged.push({
          title: existingPage.title,
          path: existingPage.path,
        });
        continue;
      }

      // Content differs and page is safe to update
      result.updated.push({
        title: existingPage.title,
        path: existingPage.path,
        reason: 'Template content updated',
      });

      if (!isPreview) {
        await prisma.wikiPage.update({
          where: { id: existingPage.id },
          data: {
            content: template.content,
            lastEditedBy: 'System Refresh',
            version: existingPage.version + 1,
            updatedAt: new Date(),
          },
        });
      }
    }

    return NextResponse.json(result);
  } catch (error) {
    console.error('POST /api/projects/[id]/wiki/refresh error:', error);
    return NextResponse.json(
      { error: 'Failed to refresh wikis' },
      { status: 500 }
    );
  }
}
